name : practice

trigger:
- main

stages:
- stage: image
  jobs:
  - job: imagebuild
    steps:
    - script: curl -fsSL https://get.docker.com -o get-docker.sh
              sh get-docker.sh
              sudo chmod 666 /var/run/docker.sock
              sudo usermod -aG docker ubuntu'     
              sudo systemctl restart docker
              docker info
