pipeline {
    agent any
    stages {
        stage('git clone') {
            steps {
                git branch: 'master', url: 'https://github.com/openmrs/openmrs-core.git'
            }
        }
        stage('docker build') {
            steps {
                sh 'docker image build -t reddy8096/open1.0 .'
                sh 'docker image push reddy8096/open1.0'
            }
        }
        stage('kubernetes') {
            steps {
                sh 'terraform init'
                sh 'terraform apply --auto-approve'
            }
        }
    }
}