pipeline {
    agent any
    stages {
        stage('docker build') {
            steps {
                sh 'docker image build -t reddy8096/noc1.0 .'
                sh 'docker image push reddy8096/noc1.0'
            }
        }
        stage('kubernetes') {
            steps {
                sh 'git clone https://github.com/hashicorp/learn-terraform-provision-eks-cluster'
                sh 'terraform init'
                sh 'terraform apply --auto-approve'
                sh 'aws eks --region $(terraform output -raw region) update-kubeconfig --name $(terraform output -raw cluster_name)'
            }
        }
    }
}
